#!/bin/sh
# array to put everythin into
result=""
# run the command 6 times
for i in {1..6}
do
  result="$result $($@)"
done

if [ $(command -v stats) ]; then
    stats $result
else
    echo $result
fi